-- 插入示例工作流市场数据
-- 确保数据表存在
USE jilang_agent;

-- 删除已存在的测试数据 (可选)
-- DELETE FROM agents WHERE name IN ('智能文档处理器', '社交媒体内容生成器', '数据可视化大师');

-- 插入示例工作流市场数据
INSERT INTO agents (name, description, type, category, icon, definition, price, purchase_count, rating, is_public, created_at, updated_at) VALUES
('智能文档处理器', '自动处理PDF、Word文档，提取关键信息并生成摘要。支持多种文件格式，批量处理效率高。', 'automation', 'data', 'document-text', '{"steps": [{"type": "file_input", "name": "文件输入", "config": {"formats": ["pdf", "docx"]}}, {"type": "text_extract", "name": "文本提取", "config": {"method": "ocr"}}, {"type": "nlp_process", "name": "信息提取", "config": {"extract": ["summary", "keywords"]}}, {"type": "output", "name": "结果输出", "config": {"format": "json"}}], "version": "1.0"}', 0, 245, 4.8, true, DATE_SUB(NOW(), INTERVAL 75 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

('社交媒体内容生成器', '根据输入的主题和风格，自动生成吸引人的社交媒体内容。支持微博、微信、抖音等多平台。', 'generator', 'content', 'megaphone', '{"steps": [{"type": "topic_input", "name": "主题输入", "config": {"required": true}}, {"type": "style_select", "name": "风格选择", "config": {"options": ["专业", "活泼", "幽默"]}}, {"type": "content_generate", "name": "内容生成", "config": {"platforms": ["weibo", "wechat", "douyin"]}}, {"type": "format_output", "name": "格式化输出", "config": {"include_hashtags": true}}], "version": "1.2"}', 50, 189, 4.6, true, DATE_SUB(NOW(), INTERVAL 55 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),

('数据可视化大师', '将Excel、CSV数据自动转换为精美的图表和报告。支持多种图表类型，一键生成专业报告。', 'analytics', 'analysis', 'chart-bar', '{"steps": [{"type": "data_import", "name": "数据导入", "config": {"formats": ["csv", "xlsx", "json"]}}, {"type": "data_clean", "name": "数据清洗", "config": {"auto_detect": true}}, {"type": "chart_generate", "name": "图表生成", "config": {"types": ["bar", "line", "pie", "scatter"]}}, {"type": "report_build", "name": "报告构建", "config": {"template": "professional"}}], "version": "2.0"}', 120, 156, 4.9, true, DATE_SUB(NOW(), INTERVAL 40 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

('邮件营销助手', '智能邮件营销工具，个性化内容生成，A/B测试，效果分析。提高邮件开启率和转换率。', 'marketing', 'automation', 'envelope', '{"steps": [{"type": "audience_segment", "name": "受众分析", "config": {"auto_segment": true}}, {"type": "content_personalize", "name": "内容个性化", "config": {"use_ai": true}}, {"type": "ab_test", "name": "A/B测试", "config": {"split_ratio": 0.5}}, {"type": "send_email", "name": "邮件发送", "config": {"schedule": true}}, {"type": "analytics", "name": "效果分析", "config": {"metrics": ["open_rate", "click_rate"]}}], "version": "1.5"}', 200, 98, 4.4, true, DATE_SUB(NOW(), INTERVAL 95 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

('语言翻译专家', '支持100+语言的智能翻译工具。保持上下文准确性，专业术语识别，批量翻译文档。', 'processor', 'nlp', 'language', '{"steps": [{"type": "text_input", "name": "文本输入", "config": {"max_length": 10000}}, {"type": "language_detect", "name": "语言检测", "config": {"confidence_threshold": 0.9}}, {"type": "translate", "name": "智能翻译", "config": {"preserve_format": true}}, {"type": "quality_check", "name": "质量检查", "config": {"grammar_check": true}}, {"type": "output", "name": "结果输出", "config": {"formats": ["text", "docx", "pdf"]}}], "version": "3.1"}', 0, 312, 4.7, true, DATE_SUB(NOW(), INTERVAL 80 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

('图像风格转换器', '将普通照片转换为艺术风格图像。支持油画、水彩、素描等多种艺术风格，一键美化图片。', 'transformer', 'content', 'photo', '{"steps": [{"type": "image_upload", "name": "图像上传", "config": {"formats": ["jpg", "png", "webp"]}}, {"type": "style_select", "name": "风格选择", "config": {"styles": ["oil_painting", "watercolor", "sketch", "cartoon"]}}, {"type": "ai_process", "name": "AI处理", "config": {"quality": "high"}}, {"type": "preview", "name": "效果预览", "config": {"allow_adjust": true}}, {"type": "download", "name": "下载结果", "config": {"resolution": "original"}}], "version": "2.3"}', 80, 167, 4.5, true, DATE_SUB(NOW(), INTERVAL 48 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),

('网站SEO优化器', '全面分析网站SEO状况，提供优化建议。关键词分析，竞争对手研究，排名监控。', 'analyzer', 'analysis', 'search', '{"steps": [{"type": "url_input", "name": "网站输入", "config": {"validate": true}}, {"type": "crawl_site", "name": "网站爬取", "config": {"depth": 3}}, {"type": "seo_analyze", "name": "SEO分析", "config": {"check_all": true}}, {"type": "keyword_research", "name": "关键词研究", "config": {"include_competitors": true}}, {"type": "report_generate", "name": "报告生成", "config": {"format": "detailed"}}], "version": "1.8"}', 150, 134, 4.6, true, DATE_SUB(NOW(), INTERVAL 60 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),

('代码质量检查器', '自动检查代码质量，发现潜在问题。支持多种编程语言，代码规范检查，安全漏洞扫描。', 'validator', 'automation', 'code', '{"steps": [{"type": "code_input", "name": "代码输入", "config": {"languages": ["python", "javascript", "java", "go"]}}, {"type": "syntax_check", "name": "语法检查", "config": {"strict_mode": true}}, {"type": "quality_scan", "name": "质量扫描", "config": {"rules": "comprehensive"}}, {"type": "security_audit", "name": "安全审计", "config": {"vulnerability_check": true}}, {"type": "report_output", "name": "报告输出", "config": {"include_fixes": true}}], "version": "2.1"}', 100, 89, 4.3, true, DATE_SUB(NOW(), INTERVAL 68 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

('会议记录转录器', '将语音会议自动转录为文字，生成会议纪要。支持多人识别，智能提取行动项和决策。', 'transcriber', 'nlp', 'microphone', '{"steps": [{"type": "audio_upload", "name": "音频上传", "config": {"formats": ["mp3", "wav", "m4a"]}}, {"type": "speech_to_text", "name": "语音转文字", "config": {"multi_speaker": true}}, {"type": "content_structure", "name": "内容结构化", "config": {"identify_topics": true}}, {"type": "action_extract", "name": "行动项提取", "config": {"smart_detection": true}}, {"type": "summary_generate", "name": "摘要生成", "config": {"format": "minutes"}}], "version": "1.7"}', 0, 278, 4.8, true, DATE_SUB(NOW(), INTERVAL 42 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

('电商数据分析师', '专为电商平台设计的数据分析工具。销售趋势分析，用户行为洞察，库存优化建议。', 'analyzer', 'analysis', 'shopping-cart', '{"steps": [{"type": "data_connect", "name": "数据连接", "config": {"platforms": ["shopify", "woocommerce", "magento"]}}, {"type": "sales_analyze", "name": "销售分析", "config": {"period": "monthly"}}, {"type": "user_behavior", "name": "用户行为分析", "config": {"track_journey": true}}, {"type": "inventory_optimize", "name": "库存优化", "config": {"predict_demand": true}}, {"type": "dashboard_create", "name": "仪表板创建", "config": {"real_time": true}}], "version": "2.2"}', 300, 67, 4.7, true, DATE_SUB(NOW(), INTERVAL 102 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY));

-- 查看插入结果
SELECT id, name, category, price, purchase_count, rating, is_public FROM agents WHERE is_public = true ORDER BY purchase_count DESC; 